apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: true
    jsonData:
      tracesToLogsV2: {}
      serviceMap: {}
      nodeGraph: {}
      search:
        hide: false
      grpcAddress: "tempo:9095"
